---
version: '3'

services:

  backend:
    # image: popstas/yandex-speechkit-talk-recognition:latest
    image: node:12
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      DATA_DIR: ${DATA_DIR}
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
    - .:/app
    - /home/popstas/yandex-stt:${DATA_DIR}
    working_dir: /app
    command:
      npm run server

  frontend:
    # image: popstas/yandex-speechkit-talk-viewer:latest
    image: node:12
    # build: data/front
    environment:
      HOST: 0.0.0.0 # for nuxt
      PORT: ${FRONT_PORT}
      SERVER_URL: ${SERVER_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
    - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - ./data/front:/app
    working_dir: /app
    command:
      npm run dev-clean
